services:
  - type: web
    name: blog-django
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Blog.wsgi:application"
    env: python
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: blog.settings.production