services:
  - type: web
    name: blog-django
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn Blog.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Blog.settings
      - key: SECRET_KEY
        generateValue: true